name: Release

on:
  push:
    branches: [main, beta]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: release-please-action
      uses: google-github-actions/release-please-action@v3.1.2
      id: release
      with:
        token: ${{ secrets.DEV_TOKEN }}
        command: manifest
        
